language: ruby
rvm:
- 2.5.3
bundler_args: --without development
sudo: false
cache:
  bundler: true
  yarn: true
  directories:
  - tmp/solr_dl/
env:
  global:
  - RAILS_ENV=test
before_install:
- docker pull solr:7.4.0
- docker run -d -p 8983:8983 -v "$(pwd)"/solr/conf:/myconfig solr:7.4.0 solr-create -c blacklight-core -d /myconfig
- docker ps -a
before_script: bundle exec rails assets:precompile
script: bundle exec rake
script: bundle exec niftany