language: ruby
rvm:
- 2.5.3
bundler_args: --without development
sudo: false
cache:
  bundler: true
  yarn: true
  directories:
  - tmp/solr_dl/
jdk: oraclejdk9
env:
  global:
  - RAILS_ENV=test
before_install:
- docker pull solr:7.4.0
- docker run -d -p 8983:8983 -v "$(pwd)"/solr/conf:/myconfig solr:7.4.0 solr-create -c blacklight-core -d /myconfig
- docker ps -a
before_script: bundle exec rails assets:precompile
script: bundle exec rake
scropt: bundle exec niftany

jobs:
  include:
    - stage: test_traject
      rvm: jruby-9.1.9.0
      script: bundle exec traject -s processing_thread_pool=5 -c lib/traject/psulib_config.rb lib/traject/fixtures.mrc

stages:
  - test_traject
  - test